import re
import os

file_path = r"d:\NEURA\prompt_engineering_11\js\views\admin-dashboard.js"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Add global interval variable at the top
if "let adminPollInterval = null;" not in content:
    content = content.replace("let newTeamMembers = ['', ''];", "let newTeamMembers = ['', ''];\nlet adminPollInterval = null;")

# 2. Modify renderAdminDashboard to fetch arena overview and handle polling
render_start_marker = "export async function renderAdminDashboard() {"
new_render_start = """export async function renderAdminDashboard() {
  const container = document.getElementById('page-admin-dashboard');
  if (!container) return;

  if (adminPollInterval) clearInterval(adminPollInterval);
  adminPollInterval = setInterval(() => {
    if (document.getElementById('page-admin-dashboard')?.classList.contains('active')) {
      renderAdminDashboard();
    } else {
      clearInterval(adminPollInterval);
    }
  }, 10000);"""

content = re.sub(
    r"export async function renderAdminDashboard\(\) \{[\s\S]*?if \(!container\) return;",
    new_render_start,
    content,
    count=1
)

# 3. Add getArenaJudgeOverview after registrations
fetch_marker = "const registrations = await store.getAdminRegistrations();"
new_fetch = """const registrations = await store.getAdminRegistrations();
  const arenaRes = await store.getArenaJudgeOverview();
  const arenaStatus = arenaRes?.success && arenaRes.arena_config ? arenaRes.arena_config.status : 'waiting';
  const isResultsReleased = arenaRes?.success && arenaRes.arena_config ? arenaRes.arena_config.is_results_released : false;
  
  const statusBadge = arenaStatus === 'live' ? '<span class="chip chip-cyan" style="animation:pulse-glow 1.5s infinite;">● LIVE ARENA</span>'
                    : arenaStatus === 'completed' ? '<span class="chip chip-violet">■ ARENA COMPLETED</span>'
                    : arenaStatus === 'results_available' || isResultsReleased ? '<span class="chip chip-green">✓ RESULTS RELEASED</span>'
                    : '<span class="chip chip-amber">⏳ WAITING FOR START</span>';
"""
if "const arenaRes =" not in content:
    content = content.replace(fetch_marker, new_fetch)

# 4. Modify the template literal to add Accordions and Arena Status Indicator
# Replace Section 1: Competition Control
comp_control_old = """    <!-- Competition Control & Timer Manager Panel -->
    <div class="glass bracket-frame mb-4" style="padding:24px;">"""
comp_control_new = """    <!-- Evaluation Link Section -->
    <div class="glass bracket-frame mb-4" style="padding:24px; border-color:var(--violet);">
      <span class="bl"></span><span class="br"></span>
      <div style="display:flex; justify-content:space-between; align-items:center;">
        <div>
          <h2 class="heading-md" style="color:var(--violet); margin-bottom:4px;">⚖️ EVALUATION & SCORING (JUDGE DASHBOARD)</h2>
          <p class="sub-text">Assign marks and verify the scores generated by the score engine. <strong>All grading happens in the Judge Dashboard.</strong></p>
        </div>
        <button class="btn btn-primary" onclick="document.querySelector('[data-route=\\'judge-dashboard\\']').click()" style="background:var(--violet); box-shadow:0 0 15px rgba(138,43,226,0.4);">
          OPEN JUDGE DASHBOARD →
        </button>
      </div>
    </div>

    <!-- Competition Control & Timer Manager Panel -->
    <details class="glass bracket-frame mb-4" open style="padding:0; overflow:hidden;">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan); display:flex; justify-content:space-between; align-items:center;">
        <span>▼ 1. COMPETITION CONTROL & ARENA STATUS</span>
        <span>${statusBadge}</span>
      </summary>
      <div style="padding:24px;">"""
content = content.replace(comp_control_old, comp_control_new)

# Close Competition details (before SECTION 0)
sec0_marker = """    <!-- ====================================================================
         SECTION 0: LIVE GOOGLE FORM REGISTRATION & DATABASE SYNC CONTROL"""
content = content.replace(sec0_marker, "      </div>\n    </details>\n\n" + sec0_marker)

# Replace Section 0 start
sec0_old = """         SECTION 0: LIVE GOOGLE FORM REGISTRATION & DATABASE SYNC CONTROL
         ==================================================================== -->
    <div class="glass bracket-frame mb-4" style="padding:26px; border-color:var(--cyan-dim);">"""
sec0_new = """         SECTION 0: LIVE GOOGLE FORM REGISTRATION & DATABASE SYNC CONTROL
         ==================================================================== -->
    <details class="glass bracket-frame mb-4" style="padding:0; overflow:hidden; border-color:var(--cyan-dim);">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan);">
        ▶ 2. GOOGLE FORM / SHEETS LIVE REGISTRATION CONTROL
      </summary>
      <div style="padding:26px;">"""
content = content.replace(sec0_old, sec0_new)

# Close Section 0 (before SECTION 1)
sec1_marker = """    <!-- ====================================================================
         SECTION 1: ADMIN TEAM REGISTRATION & PROVISIONING (EXPERT FEATURE)"""
content = content.replace(sec1_marker, "      </div>\n    </details>\n\n" + sec1_marker)

# Replace Section 1 start
sec1_old = """         SECTION 1: ADMIN TEAM REGISTRATION & PROVISIONING (EXPERT FEATURE)
         ==================================================================== -->
    <div class="glass bracket-frame mb-4" style="padding:26px; border-color:var(--cyan-dim);">"""
sec1_new = """         SECTION 1: ADMIN TEAM REGISTRATION & PROVISIONING (EXPERT FEATURE)
         ==================================================================== -->
    <details class="glass bracket-frame mb-4" style="padding:0; overflow:hidden; border-color:var(--cyan-dim);">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan);">
        ▶ 3. REGISTER NEW PARTICIPATING TEAM (MANUAL)
      </summary>
      <div style="padding:26px;">"""
content = content.replace(sec1_old, sec1_new)

# Close Section 1 (before SECTION 2)
sec2_marker = """    <!-- ====================================================================
         SECTION 2: REGISTERED TEAMS MANAGEMENT TABLE"""
content = content.replace(sec2_marker, "      </div>\n    </details>\n\n" + sec2_marker)

# Replace Section 2 start
sec2_old = """         SECTION 2: REGISTERED TEAMS MANAGEMENT TABLE
         ==================================================================== -->
    <div class="glass bracket-frame mb-4" style="padding:24px;">"""
sec2_new = """         SECTION 2: REGISTERED TEAMS MANAGEMENT TABLE
         ==================================================================== -->
    <details class="glass bracket-frame mb-4" style="padding:0; overflow:hidden;">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan);">
        ▶ 4. REGISTERED PARTICIPATING TEAMS ROSTER
      </summary>
      <div style="padding:24px;">"""
content = content.replace(sec2_old, sec2_new)

# Close Section 2 (before Phase 3)
phase3_marker = """    <!-- Phase 3: Results Publication & Official Export Panel -->"""
content = content.replace(phase3_marker, "      </div>\n    </details>\n\n" + phase3_marker)

# Replace Phase 3 start
phase3_old = """    <!-- Phase 3: Results Publication & Official Export Panel -->
    <div class="glass bracket-frame mb-4" style="padding:24px; border-color:var(--cyan-dim);">"""
phase3_new = """    <!-- Phase 3: Results Publication & Official Export Panel -->
    <details class="glass bracket-frame mb-4" style="padding:0; overflow:hidden; border-color:var(--cyan-dim);">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan);">
        ▶ 5. OFFICIAL RESULTS GATING & DATA EXPORT
      </summary>
      <div style="padding:24px;">"""
content = content.replace(phase3_old, phase3_new)

# Close Phase 3 (before Case Authoring)
case_marker = """    <!-- Case Authoring & Management Panel -->"""
content = content.replace(case_marker, "      </div>\n    </details>\n\n" + case_marker)

# Replace Case Authoring start
case_old = """    <!-- Case Authoring & Management Panel -->
    <div class="glass bracket-frame mb-4" style="padding:24px;">"""
case_new = """    <!-- Case Authoring & Management Panel -->
    <details class="glass bracket-frame mb-4" style="padding:0; overflow:hidden;">
      <summary style="padding:16px 24px; cursor:pointer; font-weight:700; background:rgba(0,0,0,0.2); border-bottom:1px solid var(--line-strong); outline:none; user-select:none; color:var(--cyan);">
        ▶ 6. BROKEN-PROMPT CASE AUTHORING & MANAGEMENT
      </summary>
      <div style="padding:24px;">"""
content = content.replace(case_old, case_new)

# Close Case Authoring
end_marker = """  `;

  attachAdminDashboardHandlers();"""
content = content.replace(end_marker, "      </div>\n    </details>\n" + end_marker)

# Fix summary styles to auto-toggle the arrow
content = content.replace("▶", "").replace("▼", "")
# Let's add standard css caret or just let native HTML5 details handle the arrow! The <summary> element natively has an arrow!

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)
print("Updated admin-dashboard.js successfully.")
