"""
NEURA Hackathon Platform -- Google Forms Webhook
================================================
Called by the Google Apps Script on every new/edited form submission.

Form structure:
  - Team Name
  - Member 1 Name  (form submitter — gets the login account)
  - Member 2 Name  (optional second team member)
  - Email          (one per team — used as login email)
  - Mobile Number  (one per team — +91 / 0 prefix stripped automatically)
  - Department
  - Year of Study

Endpoint: POST /api/v1/webhook/form-submission
"""
import re
import uuid
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, Header, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.config import settings
from app.core.audit import log_audit_event
from app.core.security import hash_password
from app.database import get_db
from app.models.hackathon import Hackathon
from app.models.registration import Registration
from app.models.team import Team, TeamMember
from app.models.user import Role, User

router = APIRouter(prefix="/webhook", tags=["Google Forms Webhook"])

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


# ── Helpers ────────────────────────────────────────────────────

def strip_phone(raw: str) -> str:
    """
    Strips non-digit characters then removes country/trunk prefixes:
      +91xxxxxxxxxx  → 10-digit number
      91xxxxxxxxxx   → 10-digit number
      0xxxxxxxxxx    → 10-digit number
    Returns the cleaned 10-digit (or best-effort) number.
    """
    digits = re.sub(r"\D", "", raw or "")
    if len(digits) == 12 and digits.startswith("91"):
        digits = digits[2:]
    elif len(digits) == 11 and digits.startswith("0"):
        digits = digits[1:]
    return digits


# ── Request schema ─────────────────────────────────────────────

class FormSubmissionPayload(BaseModel):
    """
    Sent by the Google Apps Script after every form submission / edit.
    Field names must match exactly what the Apps Script POSTs.
    """
    # Credentials generated by the Apps Script
    login_email:        str
    generated_password: str

    # Core team info from the form
    team_name:     str
    member1_name:  str                 # Member 1 — gets the login account
    member2_name:  Optional[str] = None  # Member 2 — stored, no separate login
    email:         str
    phone:         Optional[str] = None
    department:    Optional[str] = None  # Department / Branch
    year:          Optional[str] = None  # Year of Study

    # Optional metadata
    timestamp:                  Optional[str] = None
    external_registration_id:   Optional[str] = None


# ── Auth ───────────────────────────────────────────────────────

def verify_webhook_secret(x_webhook_secret: str = Header(...)):
    if x_webhook_secret != settings.WEBHOOK_SECRET:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid webhook secret."
        )


# ── Main endpoint ──────────────────────────────────────────────

@router.post("/form-submission", status_code=200)
def handle_form_submission(
    payload: FormSubmissionPayload,
    db: Session = Depends(get_db),
    _: None = Depends(verify_webhook_secret),
):
    """
    Idempotently creates or updates:
      Registration → User (Member 1 login) → Team → TeamMember links
    so the participant can log in immediately with their generated password.
    """
    email = payload.login_email.strip().lower()
    if not EMAIL_RE.match(email):
        raise HTTPException(422, detail=f"Invalid email: {email}")

    # Clean the phone number
    clean_phone = strip_phone(payload.phone or "")

    now      = datetime.utcnow()
    pwd_hash = hash_password(payload.generated_password)

    # ── 1. Upsert Registration ─────────────────────────────────
    reg    = db.query(Registration).filter(Registration.email == email).first()
    is_new = reg is None

    if is_new:
        ext_id = payload.external_registration_id or f"FORM-{uuid.uuid4().hex[:8].upper()}"
        reg = Registration(
            id=str(uuid.uuid4()),
            external_registration_id=ext_id,
            team_name=payload.team_name.strip(),
            participant_name=payload.member1_name.strip(),
            member2_name=payload.member2_name.strip() if payload.member2_name else None,
            email=email,
            phone=clean_phone,
            department=payload.department,
            year=payload.year,
            registration_status="VERIFIED",
            verification_status="VERIFIED",
            account_status="ACTIVE",
            password_hash=pwd_hash,
            password_set=True,
            is_active=True,
            source="google_forms_webhook",
            imported_at=now,
            last_synced_at=now,
        )
        db.add(reg)
    else:
        # Re-sync on edited response
        reg.team_name       = payload.team_name.strip()
        reg.participant_name = payload.member1_name.strip()
        reg.member2_name    = payload.member2_name.strip() if payload.member2_name else reg.member2_name
        reg.phone           = clean_phone or reg.phone
        reg.department      = payload.department or reg.department
        reg.year            = payload.year or reg.year
        reg.password_hash   = pwd_hash
        reg.password_set    = True
        reg.last_synced_at  = now
        reg.registration_status = "VERIFIED"
        reg.account_status      = "ACTIVE"

    db.flush()

    # ── 2. Upsert Team ─────────────────────────────────────────
    team = db.query(Team).filter(Team.name == payload.team_name.strip()).first()
    if not team:
        hk    = db.query(Hackathon).first()
        hk_id = hk.id if hk else "hk-2026"
        team  = Team(
            id=f"team-{uuid.uuid4().hex[:8]}",
            hackathon_id=hk_id,
            name=payload.team_name.strip(),
            college=payload.department or "Registered Institute",
            invite_code=f"NR-{uuid.uuid4().hex[:4].upper()}",
            status="forming",
        )
        db.add(team)
        db.flush()

    reg.team_id = team.id

    # ── 3. Upsert Member 1 User (login account) ────────────────
    user = db.query(User).filter(User.email == email).first()
    if not user:
        user = User(
            id=f"usr-{uuid.uuid4().hex[:8]}",
            name=payload.member1_name.strip(),
            email=email,
            password_hash=pwd_hash,
            affiliation=payload.department or "Participant",
            status="active",
        )
        db.add(user)
        db.flush()
        db.add(Role(user_id=user.id, name="participant"))
    else:
        # Keep password in sync with the sheet
        user.password_hash = pwd_hash
        user.name          = payload.member1_name.strip()
        user.status        = "active"

    reg.user_id = user.id

    # ── 4. TeamMember — Member 1 ───────────────────────────────
    if not db.query(TeamMember).filter(TeamMember.user_id == user.id).first():
        count = db.query(TeamMember).filter(TeamMember.team_id == team.id).count()
        db.add(TeamMember(team_id=team.id, user_id=user.id,
                          role="leader" if count == 0 else "member"))

    db.commit()
    db.refresh(reg)

    log_audit_event(
        db,
        action="registration.webhook_sync",
        target_type="Registration",
        target_id=reg.id,
        metadata={
            "email":      email,
            "team":       payload.team_name,
            "member2":    payload.member2_name,
            "department": payload.department,
            "year":       payload.year,
            "is_new":     is_new,
        },
    )

    return {
        "success":         True,
        "action":          "created" if is_new else "updated",
        "email":           email,
        "team":            team.name,
        "member1":         payload.member1_name,
        "member2":         payload.member2_name or "—",
        "department":      payload.department,
        "year":            payload.year,
        "phone_stored":    clean_phone,
        "user_id":         user.id,
        "registration_id": reg.id,
        "message":         "Team provisioned. Login is active.",
    }


# ── Liveness ping ──────────────────────────────────────────────

@router.get("/ping")
def webhook_ping():
    return {"status": "ok", "endpoint": "google_forms_webhook"}
